model:
  pretrained_model_path: "models/unsloth-gemma-3-270m-it/models--unsloth--gemma-3-270m-it/snapshots/23cf460f6bb16954176b3ddcc8d4f250501458a9"
training:
  output_dir: "checkpoints/lora_curriculum"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  max_steps: 0  # unused when curriculum is present
  learning_rate: 1e-4
  fp16: false
  logging_steps: 50
  save_steps: 200
  eval_strategy: "steps"
  eval_steps: 200
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  lr_scheduler_type: "cosine"
  warmup_steps: 100
  weight_decay: 0.01
  max_grad_norm: 1.0
  use_instruction_collator: false
lora:
  r: 16
  lora_alpha: 32
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]
  dropout: 0.05

# Curriculum phases: start with instruct for stability, add puzzles, then increase puzzles, finally add openings/commentary if available
curriculum:
  - steps: 300
    datasets:
      - path: "data/finetune/chess_finetune_refined.jsonl"
        weight: 1.0
  - steps: 500
    datasets:
      - path: "data/finetune/chess_finetune_refined.jsonl"
        weight: 0.6
      - path: "data/datasets/lichess_puzzles_1000_2000.jsonl"
        weight: 0.4
  - steps: 700
    datasets:
      - path: "data/finetune/chess_finetune_refined.jsonl"
        weight: 0.4
      - path: "data/datasets/lichess_puzzles_1000_2000.jsonl"
        weight: 0.6
  - steps: 500
    datasets:
      - path: "data/finetune/chess_finetune_refined.jsonl"
        weight: 0.3
      - path: "data/datasets/lichess_puzzles_1000_2000.jsonl"
        weight: 0.6
      # Optional additions when available:
      # - path: "data/datasets/commentary_25k.jsonl"
      #   weight: 0.05
      # - path: "data/datasets/openings_10k.jsonl"
      #   weight: 0.05

