model:
  pretrained_model_path: "models/unsloth-gemma-3-270m-it/models--unsloth--gemma-3-270m-it/snapshots/23cf460f6bb16954176b3ddcc8d4f250501458a9"
training:
  output_dir: "checkpoints/lora_uci"
  per_device_train_batch_size: 4  # Increased batch size
  gradient_accumulation_steps: 4  # Reduced accumulation
  num_train_epochs: 1
  max_steps: 2000  # More training steps
  learning_rate: 2e-4  # Higher learning rate
  fp16: false
  logging_steps: 25  # More frequent logging
  save_steps: 100  # More frequent checkpoints
  seed: 3407  # Random seed for reproducibility
  eval_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  lr_scheduler_type: "cosine"
  warmup_steps: 50  # Shorter warmup
  weight_decay: 0.01
  max_grad_norm: 1.0
  remove_unused_columns: false  # Important for instruction tuning
lora:
  r: 16  # Higher rank for better capacity
  lora_alpha: 32  # Higher alpha
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]  # Simplified modules
  dropout: 0.05
dataset:
  path: "data/standardized/standardized_uci_expert.jsonl"

